### ISSUE TITLE
For pyqt5

### ISSUE THREAD

**Issue by OpenCDR** [klecknerlab/simple_pyspin#3]
First of all, thank you for your work. I tried to use your library in pyqt5 and set up a thread for it, but an error will be reported:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/Desktop/UItest/UItest/Thread.py", line 226, in run
    img = self.cam.get_array()
  File "/usr/local/lib/python3.6/dist-packages/simple_pyspin/__init__.py", line 221, in get_array
    img = self.cam.GetNextImage(PySpin.EVENT_TIMEOUT_INFINITE if wait else PySpin.EVENT_TIMEOUT_NONE)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/PySpin.py", line 47851, in GetNextImage
    return _PySpin._SWIG_CamPtr_GetNextImage(self, *args)
_PySpin.SpinnakerException: Spinnaker: Camera is not streaming [-1010]

What can I do to solve this problem?
The thread is written as follows：

class camera(threading.Thread):
    def __init__(self,inx=0):
        super(camera, self).__init__()
        self.running = True
        self.cam = Camera(inx,False)  # Acquire Camera
        self.cam.init()

    def stop(self):
        self.running = False
        self.cam.stop()

    def run(self):
        while self.running:
            img = self.cam.get_array()
            cv2.imshow('kk', img)
            cv2.waitKey(1)

**Comment by klecknerlab** [comment]
Hi,

Please be aware that I do not provide support for this library.

That being said, I suggest you look at the examples.

Best,
Dustin

On Jan 18, 2021, at 5:32 AM, OpenCDR <notifications@github.com<mailto:notifications@github.com>> wrote:



First of all, thank you for your work. I tried to use your library in pyqt5 and set up a thread for it, but an error will be reported:

Traceback (most recent call last):
File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/home/ubuntu/Desktop/UItest/UItest/Thread.py", line 226, in run
img = self.cam.get_array()
File "/usr/local/lib/python3.6/dist-packages/simple_pyspin/init.py", line 221, in get_array
img = self.cam.GetNextImage(PySpin.EVENT_TIMEOUT_INFINITE if wait else PySpin.EVENT_TIMEOUT_NONE)
File "/home/ubuntu/.local/lib/python3.6/site-packages/PySpin.py", line 47851, in GetNextImage
return _PySpin._SWIG_CamPtr_GetNextImage(self, *args)
_PySpin.SpinnakerException: Spinnaker: Camera is not streaming [-1010]

What can I do to solve this problem?
The thread is written as follows：
class camera(threading.Thread):
def init(self,inx=0):
super(camera, self).init()
self.running = True
self.cam = Camera(inx,False) # Acquire Camera
self.cam.init()

def stop(self):
    self.running = False
    self.cam.stop()

def run(self):
    while self.running:
        img = self.cam.get_array()
        cv2.imshow('kk', img)
        cv2.waitKey(1)
